export default {
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'Feat',
        'FIX',
        'fix',
        'Fix',
        'docs',
        'Docs',
        'style',
        'Style',
        'refactor',
        'Refactor',
        'perf',
        'Perf',
        'test',
        'Test',
        'build',
        'Build',
        'ci',
        'CI',
        'chore',
        'Chore',
        'revert',
        'Revert',
      ],
    ],
    'type-case': [0, 'never'],
    'type-empty': [2, 'never'],
    'scope-empty': [0, 'never'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [2, 'always', 100],
  },
  parserPreset: {
    parserOpts: {
      headerPattern: /^(?:\[)?(\w+)(?:\(([^)]+)\))?(?:\])?(?::\s+|\s+)(.+)$/,
      headerCorrespondence: ['type', 'scope', 'subject'],
    },
  },
}
